# Generated by Django 5.1.2 on 2024-12-04 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUserCreationForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Введите имя', max_length=50, verbose_name='Имя')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Эл.почта')),
                ('image', models.ImageField(blank=True, help_text='Загрузити фотографию', null=True, upload_to='product/photo', verbose_name='фото')),
                ('phone_number', models.IntegerField(blank=True, help_text='Введите номер телефона', max_length=15, null=True, verbose_name='Номер телефона')),
                ('country', models.CharField(blank=True, help_text='Введите страну проживания', max_length=40, null=True, verbose_name='Страна')),
            ],
            options={
                'verbose_name': 'пользователь',
            },
        ),
    ]
