# Generated by Django 5.1.2 on 2024-12-09 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_user_is_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='avatars',
            new_name='avatar',
        ),
    ]
