# Generated by Django 5.1.2 on 2024-11-07 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, help_text='Загрузити фотографию', null=True, upload_to='product/photo', verbose_name='фото'),
        ),
    ]
