# Generated by Django 5.1.2 on 2024-10-30 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='title',
        ),
        migrations.AddField(
            model_name='category',
            name='description',
            field=models.TextField(blank=True, help_text='Введите описание', max_length=250, null=True, verbose_name='описание'),
        ),
        migrations.AddField(
            model_name='category',
            name='name',
            field=models.CharField(blank=True, help_text='Введите название', max_length=250, null=True, verbose_name='название'),
        ),
        migrations.AddField(
            model_name='product',
            name='cash',
            field=models.IntegerField(blank=True, help_text='Введите цену', max_length=100, null=True, verbose_name='Цена'),
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.TextField(blank=True, help_text='Введите категорию', max_length=250, null=True, verbose_name='категория'),
        ),
        migrations.AddField(
            model_name='product',
            name='created_at',
            field=models.DateField(blank=True, help_text='Введите датe создания', null=True, verbose_name='дата создания'),
        ),
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, help_text='Загрузити фотографию', null=True, upload_to='media/photo', verbose_name='фото'),
        ),
        migrations.AddField(
            model_name='product',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='дата последнего изменения'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(help_text='Введите описание', max_length=250, verbose_name='описание'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(help_text='Введите название', max_length=250, verbose_name='название'),
        ),
    ]
