# Generated by Django 5.1.2 on 2024-10-30 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_remove_category_title_category_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='cash',
        ),
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.CharField(blank=True, help_text='Введите цену', max_length=100, null=True, verbose_name='Цена'),
        ),
    ]
