# Generated by Django 5.1.2 on 2024-11-27 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_alter_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.IntegerField(blank=True, help_text='Введите цену', max_length=100, null=True, verbose_name='Цена'),
        ),
    ]
