# Generated by Django 5.1.2 on 2024-12-05 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_alter_product_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.IntegerField(blank=True, help_text='Введите цену', null=True, verbose_name='Цена'),
        ),
    ]
