# Generated by Django 5.1.2 on 2024-12-09 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_alter_product_options_product_is_available_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'permissions': [('can_unpublish_product', 'Can unpublish product'), ('remove_any_product', 'Remove any product')], 'verbose_name': 'продукт', 'verbose_name_plural': 'продукты'},
        ),
    ]
